# Generated by Django 5.2.1 on 2025-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealsAdd',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Expired', 'Expired')], max_length=10)),
                ('poster', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DealsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Used', 'Used'), ('Not_Used', 'Not_Used')], max_length=10)),
                ('min_purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.CharField(max_length=100)),
            ],
        ),
    ]
